{% for tag in image.build_tags -%}
#!BuildTag: {{ tag }}
{% endfor -%}

FROM {% if image.from_image %}{{ image.from_image }}{% else %}suse/sle15:15.{{ sp_version }}{% endif %}

MAINTAINER {{ image.maintainer }}

# Define labels according to https://en.opensuse.org/Building_derived_containers
# labelprefix={{ image.labelprefix }}
PREFIXEDLABEL org.opencontainers.image.title="{{ image.title }}"
PREFIXEDLABEL org.opencontainers.image.description="{{ image.description }}"
PREFIXEDLABEL org.opencontainers.image.version="{{ image.version_label }}"
PREFIXEDLABEL org.opencontainers.image.url="https://www.suse.com/products/server/"
PREFIXEDLABEL org.opencontainers.image.created="%BUILDTIME%"
PREFIXEDLABEL org.opencontainers.image.vendor="SUSE LLC"
PREFIXEDLABEL org.opensuse.reference="{{ image.reference }}"
PREFIXEDLABEL org.openbuildservice.disturl="%DISTURL%"
# endlabelprefix
LABEL com.suse.techpreview="1"
{% if image.extra_label_lines %}{{ image.extra_label_lines }}{% endif %}

RUN zypper -n in --no-recommends {{ image.packages }} && zypper -n clean && rm -rf /var/log/*

{{ image.env_lines }}
{% if image.entrypoint -%}ENTRYPOINT {{ image.entrypoint }}{% endif %}
{{ image.custom_end }}
