---
name: update external files
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: run update-files.sh
        run: ./update-files.sh

      - name: create a pull request with the updated files
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          commit-message: "🤖: Update external files via ./update-files.sh"
          reviewers: dcermak,brunoleon
          assignees: dcermak
          title: "🤖: Update external files"
          body: |
            This is an automated update via ./update-files.sh
          base: main
          add-paths: |
            src/bci_build/postgres/*
            src/bci_build/nginx/*
